// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: serviciosCancion.proto

package serviciosCancion

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_serviciosCancion_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_serviciosCancion_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_serviciosCancion_proto_rawDescGZIP(), []int{0}
}

type SongsByGenreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GenreName     string                 `protobuf:"bytes,1,opt,name=genreName,proto3" json:"genreName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SongsByGenreRequest) Reset() {
	*x = SongsByGenreRequest{}
	mi := &file_serviciosCancion_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SongsByGenreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SongsByGenreRequest) ProtoMessage() {}

func (x *SongsByGenreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_serviciosCancion_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SongsByGenreRequest.ProtoReflect.Descriptor instead.
func (*SongsByGenreRequest) Descriptor() ([]byte, []int) {
	return file_serviciosCancion_proto_rawDescGZIP(), []int{1}
}

func (x *SongsByGenreRequest) GetGenreName() string {
	if x != nil {
		return x.GenreName
	}
	return ""
}

type SongRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SongRequest) Reset() {
	*x = SongRequest{}
	mi := &file_serviciosCancion_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SongRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SongRequest) ProtoMessage() {}

func (x *SongRequest) ProtoReflect() protoreflect.Message {
	mi := &file_serviciosCancion_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SongRequest.ProtoReflect.Descriptor instead.
func (*SongRequest) Descriptor() ([]byte, []int) {
	return file_serviciosCancion_proto_rawDescGZIP(), []int{2}
}

func (x *SongRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type Genre struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Genre) Reset() {
	*x = Genre{}
	mi := &file_serviciosCancion_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Genre) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Genre) ProtoMessage() {}

func (x *Genre) ProtoReflect() protoreflect.Message {
	mi := &file_serviciosCancion_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Genre.ProtoReflect.Descriptor instead.
func (*Genre) Descriptor() ([]byte, []int) {
	return file_serviciosCancion_proto_rawDescGZIP(), []int{3}
}

func (x *Genre) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Genre) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Song struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Artist        string                 `protobuf:"bytes,3,opt,name=artist,proto3" json:"artist,omitempty"`
	Year          int32                  `protobuf:"varint,4,opt,name=year,proto3" json:"year,omitempty"`
	Duration      string                 `protobuf:"bytes,5,opt,name=duration,proto3" json:"duration,omitempty"`
	Genre         *Genre                 `protobuf:"bytes,6,opt,name=genre,proto3" json:"genre,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Song) Reset() {
	*x = Song{}
	mi := &file_serviciosCancion_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Song) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Song) ProtoMessage() {}

func (x *Song) ProtoReflect() protoreflect.Message {
	mi := &file_serviciosCancion_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Song.ProtoReflect.Descriptor instead.
func (*Song) Descriptor() ([]byte, []int) {
	return file_serviciosCancion_proto_rawDescGZIP(), []int{4}
}

func (x *Song) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Song) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Song) GetArtist() string {
	if x != nil {
		return x.Artist
	}
	return ""
}

func (x *Song) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *Song) GetDuration() string {
	if x != nil {
		return x.Duration
	}
	return ""
}

func (x *Song) GetGenre() *Genre {
	if x != nil {
		return x.Genre
	}
	return nil
}

type GenreList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Genres        []*Genre               `protobuf:"bytes,1,rep,name=genres,proto3" json:"genres,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenreList) Reset() {
	*x = GenreList{}
	mi := &file_serviciosCancion_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenreList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenreList) ProtoMessage() {}

func (x *GenreList) ProtoReflect() protoreflect.Message {
	mi := &file_serviciosCancion_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenreList.ProtoReflect.Descriptor instead.
func (*GenreList) Descriptor() ([]byte, []int) {
	return file_serviciosCancion_proto_rawDescGZIP(), []int{5}
}

func (x *GenreList) GetGenres() []*Genre {
	if x != nil {
		return x.Genres
	}
	return nil
}

type SongList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Songs         []*Song                `protobuf:"bytes,1,rep,name=songs,proto3" json:"songs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SongList) Reset() {
	*x = SongList{}
	mi := &file_serviciosCancion_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SongList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SongList) ProtoMessage() {}

func (x *SongList) ProtoReflect() protoreflect.Message {
	mi := &file_serviciosCancion_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SongList.ProtoReflect.Descriptor instead.
func (*SongList) Descriptor() ([]byte, []int) {
	return file_serviciosCancion_proto_rawDescGZIP(), []int{6}
}

func (x *SongList) GetSongs() []*Song {
	if x != nil {
		return x.Songs
	}
	return nil
}

var File_serviciosCancion_proto protoreflect.FileDescriptor

const file_serviciosCancion_proto_rawDesc = "" +
	"\n" +
	"\x16serviciosCancion.proto\x12\x10serviciosCancion\"\a\n" +
	"\x05Empty\"3\n" +
	"\x13SongsByGenreRequest\x12\x1c\n" +
	"\tgenreName\x18\x01 \x01(\tR\tgenreName\"#\n" +
	"\vSongRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\"+\n" +
	"\x05Genre\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xa3\x01\n" +
	"\x04Song\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06artist\x18\x03 \x01(\tR\x06artist\x12\x12\n" +
	"\x04year\x18\x04 \x01(\x05R\x04year\x12\x1a\n" +
	"\bduration\x18\x05 \x01(\tR\bduration\x12-\n" +
	"\x05genre\x18\x06 \x01(\v2\x17.serviciosCancion.GenreR\x05genre\"<\n" +
	"\tGenreList\x12/\n" +
	"\x06genres\x18\x01 \x03(\v2\x17.serviciosCancion.GenreR\x06genres\"8\n" +
	"\bSongList\x12,\n" +
	"\x05songs\x18\x01 \x03(\v2\x16.serviciosCancion.SongR\x05songs2\xe8\x01\n" +
	"\vSongService\x12A\n" +
	"\tGetGenres\x12\x17.serviciosCancion.Empty\x1a\x1b.serviciosCancion.GenreList\x12T\n" +
	"\x0fGetSongsByGenre\x12%.serviciosCancion.SongsByGenreRequest\x1a\x1a.serviciosCancion.SongList\x12@\n" +
	"\aGetSong\x12\x1d.serviciosCancion.SongRequest\x1a\x16.serviciosCancion.SongB\x13Z\x11/serviciosCancionb\x06proto3"

var (
	file_serviciosCancion_proto_rawDescOnce sync.Once
	file_serviciosCancion_proto_rawDescData []byte
)

func file_serviciosCancion_proto_rawDescGZIP() []byte {
	file_serviciosCancion_proto_rawDescOnce.Do(func() {
		file_serviciosCancion_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_serviciosCancion_proto_rawDesc), len(file_serviciosCancion_proto_rawDesc)))
	})
	return file_serviciosCancion_proto_rawDescData
}

var file_serviciosCancion_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_serviciosCancion_proto_goTypes = []any{
	(*Empty)(nil),               // 0: serviciosCancion.Empty
	(*SongsByGenreRequest)(nil), // 1: serviciosCancion.SongsByGenreRequest
	(*SongRequest)(nil),         // 2: serviciosCancion.SongRequest
	(*Genre)(nil),               // 3: serviciosCancion.Genre
	(*Song)(nil),                // 4: serviciosCancion.Song
	(*GenreList)(nil),           // 5: serviciosCancion.GenreList
	(*SongList)(nil),            // 6: serviciosCancion.SongList
}
var file_serviciosCancion_proto_depIdxs = []int32{
	3, // 0: serviciosCancion.Song.genre:type_name -> serviciosCancion.Genre
	3, // 1: serviciosCancion.GenreList.genres:type_name -> serviciosCancion.Genre
	4, // 2: serviciosCancion.SongList.songs:type_name -> serviciosCancion.Song
	0, // 3: serviciosCancion.SongService.GetGenres:input_type -> serviciosCancion.Empty
	1, // 4: serviciosCancion.SongService.GetSongsByGenre:input_type -> serviciosCancion.SongsByGenreRequest
	2, // 5: serviciosCancion.SongService.GetSong:input_type -> serviciosCancion.SongRequest
	5, // 6: serviciosCancion.SongService.GetGenres:output_type -> serviciosCancion.GenreList
	6, // 7: serviciosCancion.SongService.GetSongsByGenre:output_type -> serviciosCancion.SongList
	4, // 8: serviciosCancion.SongService.GetSong:output_type -> serviciosCancion.Song
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_serviciosCancion_proto_init() }
func file_serviciosCancion_proto_init() {
	if File_serviciosCancion_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_serviciosCancion_proto_rawDesc), len(file_serviciosCancion_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_serviciosCancion_proto_goTypes,
		DependencyIndexes: file_serviciosCancion_proto_depIdxs,
		MessageInfos:      file_serviciosCancion_proto_msgTypes,
	}.Build()
	File_serviciosCancion_proto = out.File
	file_serviciosCancion_proto_goTypes = nil
	file_serviciosCancion_proto_depIdxs = nil
}
