// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: preferencias.proto

package preferenciasGrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PreferenciasService_ObtenerPreferenciasUsuario_FullMethodName = "/co.edu.unicauca.grpc.PreferenciasService/ObtenerPreferenciasUsuario"
)

// PreferenciasServiceClient is the client API for PreferenciasService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PreferenciasServiceClient interface {
	ObtenerPreferenciasUsuario(ctx context.Context, in *PreferenciaRequest, opts ...grpc.CallOption) (*PreferenciaResponse, error)
}

type preferenciasServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPreferenciasServiceClient(cc grpc.ClientConnInterface) PreferenciasServiceClient {
	return &preferenciasServiceClient{cc}
}

func (c *preferenciasServiceClient) ObtenerPreferenciasUsuario(ctx context.Context, in *PreferenciaRequest, opts ...grpc.CallOption) (*PreferenciaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PreferenciaResponse)
	err := c.cc.Invoke(ctx, PreferenciasService_ObtenerPreferenciasUsuario_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PreferenciasServiceServer is the server API for PreferenciasService service.
// All implementations must embed UnimplementedPreferenciasServiceServer
// for forward compatibility.
type PreferenciasServiceServer interface {
	ObtenerPreferenciasUsuario(context.Context, *PreferenciaRequest) (*PreferenciaResponse, error)
	mustEmbedUnimplementedPreferenciasServiceServer()
}

// UnimplementedPreferenciasServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPreferenciasServiceServer struct{}

func (UnimplementedPreferenciasServiceServer) ObtenerPreferenciasUsuario(context.Context, *PreferenciaRequest) (*PreferenciaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ObtenerPreferenciasUsuario not implemented")
}
func (UnimplementedPreferenciasServiceServer) mustEmbedUnimplementedPreferenciasServiceServer() {}
func (UnimplementedPreferenciasServiceServer) testEmbeddedByValue()                             {}

// UnsafePreferenciasServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PreferenciasServiceServer will
// result in compilation errors.
type UnsafePreferenciasServiceServer interface {
	mustEmbedUnimplementedPreferenciasServiceServer()
}

func RegisterPreferenciasServiceServer(s grpc.ServiceRegistrar, srv PreferenciasServiceServer) {
	// If the following call pancis, it indicates UnimplementedPreferenciasServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PreferenciasService_ServiceDesc, srv)
}

func _PreferenciasService_ObtenerPreferenciasUsuario_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PreferenciaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PreferenciasServiceServer).ObtenerPreferenciasUsuario(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PreferenciasService_ObtenerPreferenciasUsuario_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PreferenciasServiceServer).ObtenerPreferenciasUsuario(ctx, req.(*PreferenciaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PreferenciasService_ServiceDesc is the grpc.ServiceDesc for PreferenciasService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PreferenciasService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "co.edu.unicauca.grpc.PreferenciasService",
	HandlerType: (*PreferenciasServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ObtenerPreferenciasUsuario",
			Handler:    _PreferenciasService_ObtenerPreferenciasUsuario_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "preferencias.proto",
}
