// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: preferencias.proto

package preferenciasGrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PreferenciaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NombreUsuario string                 `protobuf:"bytes,1,opt,name=nombreUsuario,proto3" json:"nombreUsuario,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreferenciaRequest) Reset() {
	*x = PreferenciaRequest{}
	mi := &file_preferencias_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreferenciaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreferenciaRequest) ProtoMessage() {}

func (x *PreferenciaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_preferencias_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreferenciaRequest.ProtoReflect.Descriptor instead.
func (*PreferenciaRequest) Descriptor() ([]byte, []int) {
	return file_preferencias_proto_rawDescGZIP(), []int{0}
}

func (x *PreferenciaRequest) GetNombreUsuario() string {
	if x != nil {
		return x.NombreUsuario
	}
	return ""
}

type Genero struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	NombreGenero       string                 `protobuf:"bytes,1,opt,name=nombreGenero,proto3" json:"nombreGenero,omitempty"`
	NumeroPreferencias int32                  `protobuf:"varint,2,opt,name=numeroPreferencias,proto3" json:"numeroPreferencias,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Genero) Reset() {
	*x = Genero{}
	mi := &file_preferencias_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Genero) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Genero) ProtoMessage() {}

func (x *Genero) ProtoReflect() protoreflect.Message {
	mi := &file_preferencias_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Genero.ProtoReflect.Descriptor instead.
func (*Genero) Descriptor() ([]byte, []int) {
	return file_preferencias_proto_rawDescGZIP(), []int{1}
}

func (x *Genero) GetNombreGenero() string {
	if x != nil {
		return x.NombreGenero
	}
	return ""
}

func (x *Genero) GetNumeroPreferencias() int32 {
	if x != nil {
		return x.NumeroPreferencias
	}
	return 0
}

type Artista struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	NombreArtista      string                 `protobuf:"bytes,1,opt,name=nombreArtista,proto3" json:"nombreArtista,omitempty"`
	NumeroPreferencias int32                  `protobuf:"varint,2,opt,name=numeroPreferencias,proto3" json:"numeroPreferencias,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Artista) Reset() {
	*x = Artista{}
	mi := &file_preferencias_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Artista) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Artista) ProtoMessage() {}

func (x *Artista) ProtoReflect() protoreflect.Message {
	mi := &file_preferencias_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Artista.ProtoReflect.Descriptor instead.
func (*Artista) Descriptor() ([]byte, []int) {
	return file_preferencias_proto_rawDescGZIP(), []int{2}
}

func (x *Artista) GetNombreArtista() string {
	if x != nil {
		return x.NombreArtista
	}
	return ""
}

func (x *Artista) GetNumeroPreferencias() int32 {
	if x != nil {
		return x.NumeroPreferencias
	}
	return 0
}

// NUEVO: Mensaje para preferencias de idiomas
type Idioma struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	NombreIdioma       string                 `protobuf:"bytes,1,opt,name=nombreIdioma,proto3" json:"nombreIdioma,omitempty"`
	NumeroPreferencias int32                  `protobuf:"varint,2,opt,name=numeroPreferencias,proto3" json:"numeroPreferencias,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Idioma) Reset() {
	*x = Idioma{}
	mi := &file_preferencias_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Idioma) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Idioma) ProtoMessage() {}

func (x *Idioma) ProtoReflect() protoreflect.Message {
	mi := &file_preferencias_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Idioma.ProtoReflect.Descriptor instead.
func (*Idioma) Descriptor() ([]byte, []int) {
	return file_preferencias_proto_rawDescGZIP(), []int{3}
}

func (x *Idioma) GetNombreIdioma() string {
	if x != nil {
		return x.NombreIdioma
	}
	return ""
}

func (x *Idioma) GetNumeroPreferencias() int32 {
	if x != nil {
		return x.NumeroPreferencias
	}
	return 0
}

type PreferenciaResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	IdUsuario            int32                  `protobuf:"varint,1,opt,name=idUsuario,proto3" json:"idUsuario,omitempty"`
	PreferenciasGeneros  []*Genero              `protobuf:"bytes,2,rep,name=preferenciasGeneros,proto3" json:"preferenciasGeneros,omitempty"`
	PreferenciasArtistas []*Artista             `protobuf:"bytes,3,rep,name=preferenciasArtistas,proto3" json:"preferenciasArtistas,omitempty"`
	PreferenciasIdiomas  []*Idioma              `protobuf:"bytes,4,rep,name=preferenciasIdiomas,proto3" json:"preferenciasIdiomas,omitempty"` // ← NUEVO CAMPO
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *PreferenciaResponse) Reset() {
	*x = PreferenciaResponse{}
	mi := &file_preferencias_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreferenciaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreferenciaResponse) ProtoMessage() {}

func (x *PreferenciaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_preferencias_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreferenciaResponse.ProtoReflect.Descriptor instead.
func (*PreferenciaResponse) Descriptor() ([]byte, []int) {
	return file_preferencias_proto_rawDescGZIP(), []int{4}
}

func (x *PreferenciaResponse) GetIdUsuario() int32 {
	if x != nil {
		return x.IdUsuario
	}
	return 0
}

func (x *PreferenciaResponse) GetPreferenciasGeneros() []*Genero {
	if x != nil {
		return x.PreferenciasGeneros
	}
	return nil
}

func (x *PreferenciaResponse) GetPreferenciasArtistas() []*Artista {
	if x != nil {
		return x.PreferenciasArtistas
	}
	return nil
}

func (x *PreferenciaResponse) GetPreferenciasIdiomas() []*Idioma {
	if x != nil {
		return x.PreferenciasIdiomas
	}
	return nil
}

var File_preferencias_proto protoreflect.FileDescriptor

const file_preferencias_proto_rawDesc = "" +
	"\n" +
	"\x12preferencias.proto\x12\x14co.edu.unicauca.grpc\":\n" +
	"\x12PreferenciaRequest\x12$\n" +
	"\rnombreUsuario\x18\x01 \x01(\tR\rnombreUsuario\"\\\n" +
	"\x06Genero\x12\"\n" +
	"\fnombreGenero\x18\x01 \x01(\tR\fnombreGenero\x12.\n" +
	"\x12numeroPreferencias\x18\x02 \x01(\x05R\x12numeroPreferencias\"_\n" +
	"\aArtista\x12$\n" +
	"\rnombreArtista\x18\x01 \x01(\tR\rnombreArtista\x12.\n" +
	"\x12numeroPreferencias\x18\x02 \x01(\x05R\x12numeroPreferencias\"\\\n" +
	"\x06Idioma\x12\"\n" +
	"\fnombreIdioma\x18\x01 \x01(\tR\fnombreIdioma\x12.\n" +
	"\x12numeroPreferencias\x18\x02 \x01(\x05R\x12numeroPreferencias\"\xa6\x02\n" +
	"\x13PreferenciaResponse\x12\x1c\n" +
	"\tidUsuario\x18\x01 \x01(\x05R\tidUsuario\x12N\n" +
	"\x13preferenciasGeneros\x18\x02 \x03(\v2\x1c.co.edu.unicauca.grpc.GeneroR\x13preferenciasGeneros\x12Q\n" +
	"\x14preferenciasArtistas\x18\x03 \x03(\v2\x1d.co.edu.unicauca.grpc.ArtistaR\x14preferenciasArtistas\x12N\n" +
	"\x13preferenciasIdiomas\x18\x04 \x03(\v2\x1c.co.edu.unicauca.grpc.IdiomaR\x13preferenciasIdiomas2\x88\x01\n" +
	"\x13PreferenciasService\x12q\n" +
	"\x1aObtenerPreferenciasUsuario\x12(.co.edu.unicauca.grpc.PreferenciaRequest\x1a).co.edu.unicauca.grpc.PreferenciaResponseB*Z(localClient/grpc-client/preferenciasGrpcb\x06proto3"

var (
	file_preferencias_proto_rawDescOnce sync.Once
	file_preferencias_proto_rawDescData []byte
)

func file_preferencias_proto_rawDescGZIP() []byte {
	file_preferencias_proto_rawDescOnce.Do(func() {
		file_preferencias_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_preferencias_proto_rawDesc), len(file_preferencias_proto_rawDesc)))
	})
	return file_preferencias_proto_rawDescData
}

var file_preferencias_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_preferencias_proto_goTypes = []any{
	(*PreferenciaRequest)(nil),  // 0: co.edu.unicauca.grpc.PreferenciaRequest
	(*Genero)(nil),              // 1: co.edu.unicauca.grpc.Genero
	(*Artista)(nil),             // 2: co.edu.unicauca.grpc.Artista
	(*Idioma)(nil),              // 3: co.edu.unicauca.grpc.Idioma
	(*PreferenciaResponse)(nil), // 4: co.edu.unicauca.grpc.PreferenciaResponse
}
var file_preferencias_proto_depIdxs = []int32{
	1, // 0: co.edu.unicauca.grpc.PreferenciaResponse.preferenciasGeneros:type_name -> co.edu.unicauca.grpc.Genero
	2, // 1: co.edu.unicauca.grpc.PreferenciaResponse.preferenciasArtistas:type_name -> co.edu.unicauca.grpc.Artista
	3, // 2: co.edu.unicauca.grpc.PreferenciaResponse.preferenciasIdiomas:type_name -> co.edu.unicauca.grpc.Idioma
	0, // 3: co.edu.unicauca.grpc.PreferenciasService.ObtenerPreferenciasUsuario:input_type -> co.edu.unicauca.grpc.PreferenciaRequest
	4, // 4: co.edu.unicauca.grpc.PreferenciasService.ObtenerPreferenciasUsuario:output_type -> co.edu.unicauca.grpc.PreferenciaResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_preferencias_proto_init() }
func file_preferencias_proto_init() {
	if File_preferencias_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_preferencias_proto_rawDesc), len(file_preferencias_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_preferencias_proto_goTypes,
		DependencyIndexes: file_preferencias_proto_depIdxs,
		MessageInfos:      file_preferencias_proto_msgTypes,
	}.Build()
	File_preferencias_proto = out.File
	file_preferencias_proto_goTypes = nil
	file_preferencias_proto_depIdxs = nil
}
