// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: streamingServices.proto

package streamingServices

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SongRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Format        string                 `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SongRequest) Reset() {
	*x = SongRequest{}
	mi := &file_streamingServices_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SongRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SongRequest) ProtoMessage() {}

func (x *SongRequest) ProtoReflect() protoreflect.Message {
	mi := &file_streamingServices_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SongRequest.ProtoReflect.Descriptor instead.
func (*SongRequest) Descriptor() ([]byte, []int) {
	return file_streamingServices_proto_rawDescGZIP(), []int{0}
}

func (x *SongRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SongRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

type SongPacket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SongPacket) Reset() {
	*x = SongPacket{}
	mi := &file_streamingServices_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SongPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SongPacket) ProtoMessage() {}

func (x *SongPacket) ProtoReflect() protoreflect.Message {
	mi := &file_streamingServices_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SongPacket.ProtoReflect.Descriptor instead.
func (*SongPacket) Descriptor() ([]byte, []int) {
	return file_streamingServices_proto_rawDescGZIP(), []int{1}
}

func (x *SongPacket) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_streamingServices_proto protoreflect.FileDescriptor

const file_streamingServices_proto_rawDesc = "" +
	"\n" +
	"\x17streamingServices.proto\x12\x11streamingServices\";\n" +
	"\vSongRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x16\n" +
	"\x06format\x18\x02 \x01(\tR\x06format\" \n" +
	"\n" +
	"SongPacket\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data2c\n" +
	"\fAudioService\x12S\n" +
	"\x10GetStreamingSong\x12\x1e.streamingServices.SongRequest\x1a\x1d.streamingServices.SongPacket0\x01B\x14Z\x12/streamingServicesb\x06proto3"

var (
	file_streamingServices_proto_rawDescOnce sync.Once
	file_streamingServices_proto_rawDescData []byte
)

func file_streamingServices_proto_rawDescGZIP() []byte {
	file_streamingServices_proto_rawDescOnce.Do(func() {
		file_streamingServices_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_streamingServices_proto_rawDesc), len(file_streamingServices_proto_rawDesc)))
	})
	return file_streamingServices_proto_rawDescData
}

var file_streamingServices_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_streamingServices_proto_goTypes = []any{
	(*SongRequest)(nil), // 0: streamingServices.SongRequest
	(*SongPacket)(nil),  // 1: streamingServices.SongPacket
}
var file_streamingServices_proto_depIdxs = []int32{
	0, // 0: streamingServices.AudioService.GetStreamingSong:input_type -> streamingServices.SongRequest
	1, // 1: streamingServices.AudioService.GetStreamingSong:output_type -> streamingServices.SongPacket
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_streamingServices_proto_init() }
func file_streamingServices_proto_init() {
	if File_streamingServices_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_streamingServices_proto_rawDesc), len(file_streamingServices_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_streamingServices_proto_goTypes,
		DependencyIndexes: file_streamingServices_proto_depIdxs,
		MessageInfos:      file_streamingServices_proto_msgTypes,
	}.Build()
	File_streamingServices_proto = out.File
	file_streamingServices_proto_goTypes = nil
	file_streamingServices_proto_depIdxs = nil
}
